## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'physical_measurements'  #for instance daqmx
package-url = 'https://github.com/CEMES-CNRS/pymodaq_plugins_physical_measurements' #to modify
description = 'Set of PyMoDAQ plugins for various physical measurements: multimeter, lockin, oscilloscope, indus cameras...'

author = 'SÃ©bastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pyvisa', 'bitstring', 'opencv-python']